#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AdMobFrb.Resource", IsApplication=true)]

namespace AdMobFrb
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.1.0.5")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int fragment_fast_out_extra_slow_in = 2130771968;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public const int fragment_close_enter = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int fragment_close_exit = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int fragment_fade_enter = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int fragment_fade_exit = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int fragment_open_enter = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int fragment_open_exit = 2130837509;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F030000
			public const int adSize = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int adSizes = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int adUnitId = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int alpha = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int font = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int fontProviderAuthority = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int fontProviderCerts = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int fontProviderFetchStrategy = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int fontProviderFetchTimeout = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int fontProviderPackage = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int fontProviderQuery = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int fontStyle = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int fontVariationSettings = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int fontWeight = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int ttcIndex = 2130903054;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F040000
			public const int enable_system_alarm_service_default = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int enable_system_foreground_service_default = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int enable_system_job_service_default = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int workmanager_test_configuration = 2130968579;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F050000
			public const int androidx_core_ripple_material_light = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int androidx_core_secondary_text_default_material_light = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int notification_action_color_filter = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int notification_icon_bg_color = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F060000
			public const int compat_button_inset_horizontal_material = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int compat_button_inset_vertical_material = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int compat_button_padding_horizontal_material = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int compat_button_padding_vertical_material = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int compat_control_corner_material = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int compat_notification_large_icon_max_height = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int compat_notification_large_icon_max_width = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int notification_action_icon_size = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int notification_action_text_size = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int notification_big_circle_margin = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int notification_content_margin_start = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int notification_large_icon_height = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int notification_large_icon_width = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int notification_main_column_padding_top = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int notification_media_narrow_margin = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int notification_right_icon_size = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int notification_right_side_padding_top = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int notification_small_icon_background_padding = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int notification_small_icon_size_as_large = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int notification_subtext_size = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int notification_top_pad = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int notification_top_pad_large_text = 2131099669;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F070000
			public const int Icon = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int notification_action_background = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int notification_bg = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int notification_bg_low = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int notification_bg_low_normal = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int notification_bg_low_pressed = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int notification_bg_normal = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int notification_bg_normal_pressed = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int notification_icon_background = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int notification_template_icon_bg = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int notification_template_icon_low_bg = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int notification_tile_bg = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int notify_panel_notification_icon_bg = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int Splash = 2131165197;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F080000
			public const int accessibility_action_clickable_span = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int accessibility_custom_action_0 = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int accessibility_custom_action_1 = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int accessibility_custom_action_10 = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int accessibility_custom_action_11 = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int accessibility_custom_action_12 = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int accessibility_custom_action_13 = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int accessibility_custom_action_14 = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int accessibility_custom_action_15 = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int accessibility_custom_action_16 = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int accessibility_custom_action_17 = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int accessibility_custom_action_18 = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int accessibility_custom_action_19 = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int accessibility_custom_action_2 = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int accessibility_custom_action_20 = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int accessibility_custom_action_21 = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int accessibility_custom_action_22 = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int accessibility_custom_action_23 = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int accessibility_custom_action_24 = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int accessibility_custom_action_25 = 2131230739;
			
			// aapt resource value: 0x7F080014
			public const int accessibility_custom_action_26 = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int accessibility_custom_action_27 = 2131230741;
			
			// aapt resource value: 0x7F080016
			public const int accessibility_custom_action_28 = 2131230742;
			
			// aapt resource value: 0x7F080017
			public const int accessibility_custom_action_29 = 2131230743;
			
			// aapt resource value: 0x7F080018
			public const int accessibility_custom_action_3 = 2131230744;
			
			// aapt resource value: 0x7F080019
			public const int accessibility_custom_action_30 = 2131230745;
			
			// aapt resource value: 0x7F08001A
			public const int accessibility_custom_action_31 = 2131230746;
			
			// aapt resource value: 0x7F08001B
			public const int accessibility_custom_action_4 = 2131230747;
			
			// aapt resource value: 0x7F08001C
			public const int accessibility_custom_action_5 = 2131230748;
			
			// aapt resource value: 0x7F08001D
			public const int accessibility_custom_action_6 = 2131230749;
			
			// aapt resource value: 0x7F08001E
			public const int accessibility_custom_action_7 = 2131230750;
			
			// aapt resource value: 0x7F08001F
			public const int accessibility_custom_action_8 = 2131230751;
			
			// aapt resource value: 0x7F080020
			public const int accessibility_custom_action_9 = 2131230752;
			
			// aapt resource value: 0x7F080025
			public const int actions = 2131230757;
			
			// aapt resource value: 0x7F080021
			public const int action_container = 2131230753;
			
			// aapt resource value: 0x7F080022
			public const int action_divider = 2131230754;
			
			// aapt resource value: 0x7F080023
			public const int action_image = 2131230755;
			
			// aapt resource value: 0x7F080024
			public const int action_text = 2131230756;
			
			// aapt resource value: 0x7F080026
			public const int async = 2131230758;
			
			// aapt resource value: 0x7F080027
			public const int blocking = 2131230759;
			
			// aapt resource value: 0x7F080028
			public const int chronometer = 2131230760;
			
			// aapt resource value: 0x7F080029
			public const int dialog_button = 2131230761;
			
			// aapt resource value: 0x7F08002A
			public const int forever = 2131230762;
			
			// aapt resource value: 0x7F08002B
			public const int fragment_container_view_tag = 2131230763;
			
			// aapt resource value: 0x7F08002C
			public const int icon = 2131230764;
			
			// aapt resource value: 0x7F08002D
			public const int icon_group = 2131230765;
			
			// aapt resource value: 0x7F08002E
			public const int info = 2131230766;
			
			// aapt resource value: 0x7F08002F
			public const int italic = 2131230767;
			
			// aapt resource value: 0x7F080030
			public const int line1 = 2131230768;
			
			// aapt resource value: 0x7F080031
			public const int line3 = 2131230769;
			
			// aapt resource value: 0x7F080032
			public const int normal = 2131230770;
			
			// aapt resource value: 0x7F080033
			public const int notification_background = 2131230771;
			
			// aapt resource value: 0x7F080034
			public const int notification_main_column = 2131230772;
			
			// aapt resource value: 0x7F080035
			public const int notification_main_column_container = 2131230773;
			
			// aapt resource value: 0x7F080036
			public const int right_icon = 2131230774;
			
			// aapt resource value: 0x7F080037
			public const int right_side = 2131230775;
			
			// aapt resource value: 0x7F080038
			public const int special_effects_controller_view_tag = 2131230776;
			
			// aapt resource value: 0x7F080039
			public const int tag_accessibility_actions = 2131230777;
			
			// aapt resource value: 0x7F08003A
			public const int tag_accessibility_clickable_spans = 2131230778;
			
			// aapt resource value: 0x7F08003B
			public const int tag_accessibility_heading = 2131230779;
			
			// aapt resource value: 0x7F08003C
			public const int tag_accessibility_pane_title = 2131230780;
			
			// aapt resource value: 0x7F08003D
			public const int tag_screen_reader_focusable = 2131230781;
			
			// aapt resource value: 0x7F08003E
			public const int tag_transition_group = 2131230782;
			
			// aapt resource value: 0x7F08003F
			public const int tag_unhandled_key_event_manager = 2131230783;
			
			// aapt resource value: 0x7F080040
			public const int tag_unhandled_key_listeners = 2131230784;
			
			// aapt resource value: 0x7F080041
			public const int text = 2131230785;
			
			// aapt resource value: 0x7F080042
			public const int text2 = 2131230786;
			
			// aapt resource value: 0x7F080043
			public const int time = 2131230787;
			
			// aapt resource value: 0x7F080044
			public const int title = 2131230788;
			
			// aapt resource value: 0x7F080045
			public const int view_tree_lifecycle_owner = 2131230789;
			
			// aapt resource value: 0x7F080046
			public const int view_tree_saved_state_registry_owner = 2131230790;
			
			// aapt resource value: 0x7F080047
			public const int view_tree_view_model_store_owner = 2131230791;
			
			// aapt resource value: 0x7F080048
			public const int visible_removing_fragment_view_tag = 2131230792;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F090000
			public const int google_play_services_version = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int status_bar_notification_info_maxnum = 2131296257;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F0A0000
			public const int custom_dialog = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int notification_action = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int notification_action_tombstone = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int notification_template_custom_big = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int notification_template_icon_group = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int notification_template_part_chronometer = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int notification_template_part_time = 2131361798;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0B0000
			public const int ApplicationName = 2131427328;
			
			// aapt resource value: 0x7F0B0002
			public const int common_google_play_services_unknown_issue = 2131427330;
			
			// aapt resource value: 0x7F0B0001
			public const int Hello = 2131427329;
			
			// aapt resource value: 0x7F0B0003
			public const int status_bar_notification_info_overflow = 2131427331;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0C0000
			public const int TextAppearance_Compat_Notification = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int TextAppearance_Compat_Notification_Info = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int TextAppearance_Compat_Notification_Line2 = 2131492866;
			
			// aapt resource value: 0x7F0C0003
			public const int TextAppearance_Compat_Notification_Time = 2131492867;
			
			// aapt resource value: 0x7F0C0004
			public const int TextAppearance_Compat_Notification_Title = 2131492868;
			
			// aapt resource value: 0x7F0C0005
			public const int Theme_IAPTheme = 2131492869;
			
			// aapt resource value: 0x7F0C0006
			public const int Theme_Splash = 2131492870;
			
			// aapt resource value: 0x7F0C0007
			public const int Widget_Compat_NotificationActionContainer = 2131492871;
			
			// aapt resource value: 0x7F0C0008
			public const int Widget_Compat_NotificationActionText = 2131492872;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F030000,0x7F030001,0x7F030002 }
			public static int[] AdsAttrs = new int[] {
					2130903040,
					2130903041,
					2130903042};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F030003 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130903043};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F030005,0x7F030006,0x7F030007,0x7F030008,0x7F030009,0x7F03000A }
			public static int[] FontFamily = new int[] {
					2130903045,
					2130903046,
					2130903047,
					2130903048,
					2130903049,
					2130903050};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F030004,0x7F03000B,0x7F03000C,0x7F03000D,0x7F03000E }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130903044,
					2130903051,
					2130903052,
					2130903053,
					2130903054};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x1010003,0x10100D0,0x10100D1 }
			public static int[] Fragment = new int[] {
					16842755,
					16842960,
					16842961};
			
			// aapt resource value: { 0x1010003,0x10100D1 }
			public static int[] FragmentContainerView = new int[] {
					16842755,
					16842961};
			
			// aapt resource value: 0
			public const int FragmentContainerView_android_name = 0;
			
			// aapt resource value: 1
			public const int FragmentContainerView_android_tag = 1;
			
			// aapt resource value: 1
			public const int Fragment_android_id = 1;
			
			// aapt resource value: 0
			public const int Fragment_android_name = 0;
			
			// aapt resource value: 2
			public const int Fragment_android_tag = 2;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
