<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

	<ItemGroup>
		<Compile Include="..\..\..\Glue\OfficialPlugins\FRBDKUpdater\FrbdkUpdaterSettings.cs" Link="FrbdkUpdaterSettings.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\..\Gum\GumCommon\GumCommon.csproj" />
		<ProjectReference Include="..\..\..\Localization\Localization.csproj" />
	</ItemGroup>

</Project>
