using System;
using System.Diagnostics;
using System.IO;

namespace GlueFormsCore.Plugins.EmbeddedPlugins.AboutPlugin;

internal static class DailyBuildUpdateLauncher
{
    const int MaximumFileOperationAttempts = 10;

    public static ProcessStartInfo CreateStartInfo(
        int glueProcessId,
        string installDirectory,
        string stagedDirectory,
        string applicationPath)
    {
        ArgumentException.ThrowIfNullOrEmpty(installDirectory);
        ArgumentException.ThrowIfNullOrEmpty(stagedDirectory);
        ArgumentException.ThrowIfNullOrEmpty(applicationPath);

        var script = string.Join(Environment.NewLine, new[]
        {
            "$ErrorActionPreference = 'Stop'",
            $"$installDirectory = {ToPowerShellString(installDirectory)}",
            $"$stagedDirectory = {ToPowerShellString(stagedDirectory)}",
            $"$applicationPath = {ToPowerShellString(applicationPath)}",
            "$stagedApplicationPath = Join-Path -Path $stagedDirectory -ChildPath 'GlueFormsCore.exe'",
            "$logDirectory = Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'FlatRedBall'",
            "$logPath = Join-Path $logDirectory 'GlueDailyBuildUpdate.log'",
            "function Write-UpdateLog",
            "{",
            "    param([string]$message)",
            "    try",
            "    {",
            "        Add-Content -LiteralPath $logPath -Value \"$(Get-Date -Format o) $message\"",
            "    }",
            "    catch",
            "    {",
            "    }",
            "}",
            "function Get-LockingProcesses",
            "{",
            "    param([string]$directory)",
            "    try",
            "    {",
            "        if ($null -eq ('GlueUpdateRestartManager' -as [type]))",
            "        {",
            "Add-Type -TypeDefinition @'",
            "using System;",
            "using System.Collections.Generic;",
            "using System.Runtime.InteropServices;",
            "using System.Runtime.InteropServices.ComTypes;",
            "",
            "[StructLayout(LayoutKind.Sequential)]",
            "public struct GlueUpdateRmUniqueProcess",
            "{",
            "    public int ProcessId;",
            "    public FILETIME ProcessStartTime;",
            "}",
            "",
            "[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]",
            "public struct GlueUpdateRmProcessInfo",
            "{",
            "    public GlueUpdateRmUniqueProcess Process;",
            "    [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 256)] public string ApplicationName;",
            "    [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)] public string ServiceShortName;",
            "    public int ApplicationType;",
            "    public uint ApplicationStatus;",
            "    public uint TerminalSessionId;",
            "    [MarshalAs(UnmanagedType.Bool)] public bool Restartable;",
            "}",
            "",
            "public static class GlueUpdateRestartManager",
            "{",
            "    const int ErrorMoreData = 234;",
            "",
            "    [DllImport(\"rstrtmgr.dll\", CharSet = CharSet.Unicode)]",
            "    static extern int RmStartSession(out uint sessionHandle, int sessionFlags, string sessionKey);",
            "",
            "    [DllImport(\"rstrtmgr.dll\", CharSet = CharSet.Unicode)]",
            "    static extern int RmRegisterResources(uint sessionHandle, uint fileCount, string[] fileNames, uint applicationCount, IntPtr applications, uint serviceCount, string[] serviceNames);",
            "",
            "    [DllImport(\"rstrtmgr.dll\")]",
            "    static extern int RmGetList(uint sessionHandle, out uint needed, ref uint count, [In, Out] GlueUpdateRmProcessInfo[] processInfo, ref uint rebootReasons);",
            "",
            "    [DllImport(\"rstrtmgr.dll\")]",
            "    static extern int RmEndSession(uint sessionHandle);",
            "",
            "    public static string[] GetLockOwners(string[] fileNames)",
            "    {",
            "        uint sessionHandle;",
            "        var startResult = RmStartSession(out sessionHandle, 0, Guid.NewGuid().ToString());",
            "        if (startResult != 0) return new[] { \"RmStartSession failed: \" + startResult };",
            "",
            "        try",
            "        {",
            "            var registerResult = RmRegisterResources(sessionHandle, (uint)fileNames.Length, fileNames, 0, IntPtr.Zero, 0, null);",
            "            if (registerResult != 0) return new[] { \"RmRegisterResources failed: \" + registerResult };",
            "",
            "            uint needed = 0;",
            "            uint count = 0;",
            "            uint rebootReasons = 0;",
            "            var result = RmGetList(sessionHandle, out needed, ref count, null, ref rebootReasons);",
            "            if (result == 0) return Array.Empty<string>();",
            "            if (result != ErrorMoreData) return new[] { \"RmGetList failed: \" + result };",
            "",
            "            var processInfo = new GlueUpdateRmProcessInfo[needed];",
            "            count = needed;",
            "            result = RmGetList(sessionHandle, out needed, ref count, processInfo, ref rebootReasons);",
            "            if (result != 0) return new[] { \"RmGetList failed: \" + result };",
            "",
            "            var owners = new List<string>();",
            "            for (var index = 0; index < count; index++)",
            "            {",
            "                owners.Add(processInfo[index].Process.ProcessId + \" \" + processInfo[index].ApplicationName + \" restartable=\" + processInfo[index].Restartable);",
            "            }",
            "            return owners.ToArray();",
            "        }",
            "        finally",
            "        {",
            "            RmEndSession(sessionHandle);",
            "        }",
            "    }",
            "}",
            "'@",
            "        }",
            "",
            "        $candidateFiles = @(Get-ChildItem -LiteralPath $directory -File -Force -Recurse | Select-Object -First 128 -ExpandProperty FullName)",
            "        Write-UpdateLog \"Restart Manager lock owners for ${directory}:\"",
            "        if ($candidateFiles.Count -eq 0)",
            "        {",
            "            Write-UpdateLog 'No files remained to inspect.'",
            "            return",
            "        }",
            "",
            "        $owners = [GlueUpdateRestartManager]::GetLockOwners([string[]]$candidateFiles)",
            "        if ($owners.Count -eq 0)",
            "        {",
            "            Write-UpdateLog 'Restart Manager reported no lock owners.'",
            "        }",
            "        else",
            "        {",
            "            foreach ($owner in $owners)",
            "            {",
            "                Write-UpdateLog $owner",
            "            }",
            "        }",
            "    }",
            "    catch",
            "    {",
            "        Write-UpdateLog \"Could not collect lock owners: $($_.Exception.Message)\"",
            "    }",
            "}",
            string.Empty,
            "try",
            "{",
            "    New-Item -ItemType Directory -Path $logDirectory -Force | Out-Null",
            "    Write-UpdateLog \"Update helper started. HelperPid=$PID CurrentDirectory=$($PWD.Path) InstallDirectory=$installDirectory StagedDirectory=$stagedDirectory\"",
            $"    $glueProcess = Get-Process -Id {glueProcessId} -ErrorAction SilentlyContinue",
            "    if ($null -ne $glueProcess)",
            "    {",
            "        Write-UpdateLog 'Waiting for Glue process to exit.'",
            $"        Wait-Process -Id {glueProcessId}",
            "    }",
            "    Write-UpdateLog 'Glue process has exited.'",
            string.Empty,
            $"    for ($attempt = 1; $attempt -le {MaximumFileOperationAttempts}; $attempt++)",
            "    {",
            "        try",
            "        {",
            "            Write-UpdateLog \"Starting remove attempt $attempt.\"",
            "            Remove-Item -LiteralPath $installDirectory -Recurse -Force -ErrorAction Stop",
            "            Write-UpdateLog \"Remove attempt $attempt succeeded.\"",
            "            break",
            "        }",
            "        catch",
            "        {",
            "            Write-UpdateLog \"Remove attempt $attempt failed: $($_.Exception.Message)\"",
            "            Get-LockingProcesses $installDirectory",
            $"            if ($attempt -eq {MaximumFileOperationAttempts})",
            "            {",
            "                throw",
            "            }",
            string.Empty,
            "            Start-Sleep -Seconds 1",
            "        }",
            "    }",
            string.Empty,
            $"    for ($attempt = 1; $attempt -le {MaximumFileOperationAttempts}; $attempt++)",
            "    {",
            "        try",
            "        {",
            "            Write-UpdateLog \"Starting move attempt $attempt.\"",
            "            Move-Item -LiteralPath $stagedDirectory -Destination $installDirectory -ErrorAction Stop",
            "            Write-UpdateLog \"Move attempt $attempt succeeded.\"",
            "            break",
            "        }",
            "        catch",
            "        {",
            $"            if ($attempt -eq {MaximumFileOperationAttempts})",
            "            {",
            "                throw",
            "            }",
            string.Empty,
            "            Start-Sleep -Seconds 1",
            "        }",
            "    }",
            string.Empty,
            "    Write-UpdateLog \"Starting replacement application: $applicationPath\"",
            "    Start-Process -FilePath $applicationPath",
            "    Write-UpdateLog 'Replacement application started.'",
            "}",
            "catch",
            "{",
            "    Write-UpdateLog \"Update helper reached fallback: $($_.Exception.Message)\"",
            "    Get-LockingProcesses $installDirectory",
            "    Add-Type -AssemblyName PresentationFramework",
            "    if (Test-Path -LiteralPath $stagedApplicationPath)",
            "    {",
            "        $restartPath = $stagedApplicationPath",
            "        $title = 'Glue update installed'",
            "        $message = \"Glue could not replace the existing installation because it is in use. The updated daily build will start from its staged folder.`n`n$($_.Exception.Message)`n`nDiagnostics: $logPath\"",
            "        $image = [System.Windows.MessageBoxImage]::Information",
            "    }",
            "    else",
            "    {",
            "        $restartPath = $applicationPath",
            "        $title = 'Glue update failed'",
            "        $message = \"Glue could not install the daily build. Glue will restart without updating.`n`n$($_.Exception.Message)`n`nDiagnostics: $logPath\"",
            "        $image = [System.Windows.MessageBoxImage]::Error",
            "    }",
            "    [System.Windows.MessageBox]::Show(",
            "        $message,",
            "        $title,",
            "        [System.Windows.MessageBoxButton]::OK,",
            "        $image) | Out-Null",
            string.Empty,
            "    if (Test-Path -LiteralPath $restartPath)",
            "    {",
            "        Start-Process -FilePath $restartPath",
            "    }",
            "}"
        });

        var startInfo = new ProcessStartInfo("powershell.exe")
        {
            CreateNoWindow = true,
            UseShellExecute = false,
            WindowStyle = ProcessWindowStyle.Hidden,
            WorkingDirectory = Path.GetDirectoryName(installDirectory) ?? Path.GetTempPath()
        };

        startInfo.ArgumentList.Add("-NoProfile");
        startInfo.ArgumentList.Add("-NonInteractive");
        startInfo.ArgumentList.Add("-WindowStyle");
        startInfo.ArgumentList.Add("Hidden");
        startInfo.ArgumentList.Add("-Command");
        startInfo.ArgumentList.Add(script);

        return startInfo;
    }

    static string ToPowerShellString(string value) => $"'{value.Replace("'", "''")}'";
}
