<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <DefineConstants>FNA;WEB;BLAZORGL</DefineConstants>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
    <PackageId>FlatRedBall.StateInterpolation.Kni.Web</PackageId>
    <Title>FlatRedBall State Interpolation (Web)</Title>
    <Authors>FlatRedBall</Authors>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Description>Tweening and state interpolation for FlatRedBall</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>1.0.0</Version>

  </PropertyGroup>
  <Import Project="..\..\..\..\..\FRBDK\Glue\StateInterpolationPlugin\StateInterpolationPlugin\StateInterpolationShared.projitems" Label="Shared" />
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\FlatRedBallXNA\KniWeb\FlatRedBallKniWeb.csproj" />
  </ItemGroup>
</Project>
