#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_POPUP                               4
#define IDD_CHOOSEFONT                          101
#define IDR_IMG_MENU                            103
#define IDR_IMG_ACCEL                           104
#define IDR_MENU                                105
#define IDR_ACCELERATOR                         106
#define IDD_ABOUT                               108
#define IDI_ICON1                               109
#define IDD_ICONIMAGE                           113
#define IDR_IMG_MGR_MENU                        114
#define IDD_EXPORT                              115
#define IDC_FONT                                1001
#define IDC_XOFFSET                             1001
#define IDC_FONTSIZE                            1003
#define IDC_ANTIALIASING                        1005
#define IDC_BOLD                                1006
#define IDC_WIDTH                               1007
#define IDC_HEIGHT                              1008
#define IDC_SPACE_UP                            1009
#define IDC_SPACE_RIGHT                         1010
#define IDC_SPACE_DOWN                          1011
#define IDC_SPACE_LEFT                          1012
#define IDC_BIT8                                1013
#define IDC_SPACE_HORIZ                         1014
#define IDC_SPACE_VERT                          1015
#define IDC_SMOOTH                              1016
#define IDC_SPINSAMPLING                        1017
#define IDC_ITALIC                              1018
#define IDC_SIZESPIN                            1019
#define IDC_BIT32                               1020
#define IDC_URL1                                1020
#define IDC_CHARSET                             1022
#define IDC_SCALEH                              1023
#define IDC_SCALEH_SPIN                         1024
#define IDC_DESC_TEXT                           1025
#define IDC_DESC_XML                            1026
#define IDC_USEUNICODE                          1027
#define IDC_4CHNLPACK                           1029
#define IDB_STATEIMAGES                         1030
#define IDC_URL_LIBPNG                          1031
#define IDC_URL_ZLIB                            1032
#define IDC_TEXTURE_FMT                         1033
#define IDC_DESC_BIN                            1034
#define IDC_TEXTURE_COMPRESSION                 1035
#define IDC_FILE                                1036
#define IDC_BROWSE                              1037
#define IDC_ID                                  1038
#define IDC_SQUISH                              1039
#define IDC_LIBJPEG                             1040
#define IDC_OUTLINETHICKNESS                    1043
#define IDC_SPINTHICKNESS                       1044
#define IDC_USEOEM                              1046
#define IDC_ALPHA                               1047
#define IDC_INVALIDCHAR                         1048
#define IDC_RED                                 1048
#define IDC_GREEN                               1049
#define IDC_MATCHCHARHEIGHT                     1049
#define IDC_BLUE                                1050
#define IDC_ENABLEAA                            1050
#define IDC_PRESETS                             1051
#define IDC_VIEW_SCALE_1_8                      40002
#define IDC_VIEW_SCALE_1_2                      40003
#define IDC_VIEW_SCALE_1_4                      40004
#define IDC_VIEW_SCALE_2_1                      40005
#define IDC_VIEW_SCALE_4_1                      40006
#define IDC_VIEW_SCALE_8_1                      40007
#define IDC_VIEW_SCALE_1_1                      40008
#define ID_OPTIONS_SELECTFONT                   40010
#define ID_OPTIONS_VISUALIZE                    40011
#define ID_EDIT_SELECTALL                       40012
#define ID_OPTIONS_SAVEAS                       40013
#define IDC_VIEW_NEXTPAGE                       40016
#define IDC_VIEW_PREVPAGE                       40017
#define ID_OPTIONS_ABOUT                        40018
#define ID_POPUP_UNSELECTSUBSET                 40019
#define ID_OPTIONS_ABORT                        40020
#define ID_POPUP_SELECTSUBSET                   40021
#define ID_EDIT_SELECTCHARSFROMFILE             40022
#define ID_OPTIONS_SAVECONFIGURATIONAS          40023
#define ID_OPTIONS_LOADCONFIGURATION            40024
#define ID_EDIT_FINDNEXTFAILEDCHAR              40026
#define ID_EDIT_CLEARFAILEDCHARACTERS           40028
#define ID_EDIT_OPENIMAGEMANAGER                40030
#define ID_IMAGE_IMPORTIMAGE                    40031
#define ID_IMAGE_DELETESELECTED                 40032
#define ID_IMAGE_EDIT                           40033
#define ID_EDIT_CLEARALL                        40034
#define ID_OPTIONS_EXPORTOPTIONS                40035
#define ID_APP_EXIT                             57665
#define IDC_INV_A                               57666
#define IDC_INV_G                               57670
#define IDC_INV_R                               57671
#define IDC_INV_B                               57673
#define IDC_YOFFSET                             57674
#define IDC_ADVANCE                             57676
#define IDC_SPIN_ADVANCE                        57678
#define IDC_SPIN_XOFFSET                        57680
#define IDC_SPIN_YOFFSET                        57682
